apiVersion: v1
kind: Service
metadata:
  name: car-price-service
spec:
  selector:
    app: car_price
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the cluster
      targetPort: 6000 # Port your container listens on
      nodePort: 25000  # Optional fixed NodePort
  type: NodePort
